### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by agerlach** [afrl-rq/OpenAMASE#13]
When I run `ant jar` I get the following build failure

```
-do-compile:
    [javac] Compiling 313 source files to .../OpenAMASE/OpenAMASE/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] error: Source option 7 is no longer supported. Use 8 or later.
    [javac] error: Target option 7 is no longer supported. Use 8 or later.

BUILD FAILED
...OpenAMASE/OpenAMASE/nbproject/build-impl.xml:948: The following error occurred while executing this line:
...OpenAMASE/OpenAMASE/nbproject/build-impl.xml:298: Compile failed; see the compiler error output for details.
```

I am currently running:
```
╰─ java --version
openjdk 18.0.2.1 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

**Comment by lhumphrey** [comment]
It seems that you're using a newer version of the Java platform. With 17.0.2, `ant jar` produces warnings such as `source value 7 is obsolete and will be removed in a future release` along with other warnings about certain syntax about `Integer(int)` being removed. It looks like the `build.xml` file essentially references a build file in directory `nbproject` produced by a NetBeans project.

OpenAMASE and its build file need to be updated. I think the easiest way to fix this will be to take a system with a newer version of the Java platform and have NetBeans re-generate a build file. Likely the use of `Integer(int)` a few places in the code will have to be updated as well. I'll see if I can find time to fix this at some point.

**Comment by agerlach** [comment]
OK. Thanks. Do you know if JAVA builds are portable? E.g. could I build in docker and then copy to the host?

**Comment by lhumphrey** [comment]
If you're talking about building a JAR using say 17.0.2 in Docker, then copying that JAR and running it on a system using a JRE associated with 18.0.2, I don't think that will work in this case because of the types features that were deprecated and removed. But you could try it!

**Comment by lhumphrey** [comment]
The main issue appears to be the build file created by NetBeans and leveraged by `ant`. It was specifying JDK 7, which is out of date. I've updated it to JDK 11, which is the standard on Ubuntu 22. It seems to build just fine with newer versions of the JDK as well. There are still warnings about some methods being deprecated in future versions of Java, but I'll open a separate issue for those if I can't fix them soon.

**Comment by agerlach** [comment]
Thank you!
