### ISSUE TITLE
finalize() will be deprecated in future versions of Java

### ISSUE THREAD

**Issue by lhumphrey** [afrl-rq/OpenAMASE#16]
Recently, we noticed the Java compiler is issuing warnings about "finalize()" eventually being deprecated. There are many publicly available articles that discuss the reasons for this. There are only a few instances of "finalize()" being implemented in OpenAMASE, but they will need to be addressed eventually. As far as I know, no explicit version or date has been set, so this is probably a few years away.

**Comment by lhumphrey** [comment]
It should also be noted that this will apply to 3rd party libraries that OpenAMASE uses: Flexdock, GRAL, SwingX, and Worldwind. Hopefully the maintainers will address this, and all the OpenAMASE maintainers will need to do is pull in updated source code.

**Comment by VVCAS-Sean** [comment]
Fixed by pull request #22
