### ISSUE TITLE
Need Help Please!

### ISSUE THREAD

**Issue by schoon1990** [afrl-rq/OpenAMASE#4]
Hello,

I am trying to use AMASE for  project I am trying to work on at AFIT. I am trying to output the footprint that the gimbal produces on the map to cross reference it to a moving target. Once the target is inside the footprint, it will stop the execution. Does anyone know how to get this output from AMASE from python? Thank you.

**Comment by lhumphrey** [comment]
Hi,

I've attached a Python script to get this information from AMASE. It's
configurable but currently set up to work with
OpenUxAS/examples/02_Example_WaterwaySearch. You can see at the bottom of
the script that it sets ID to 500 (one of the Air Vehicle IDs for that
scenario) and the PayloadID to 10001 (the PayloadID for that Air Vehicle's
camera).

Assuming you're on Linux, if you drop that script in the directory
OpenUxAS/examples/02_Example_WaterwaySearch, then run the following two
commands in two separate terminal windows:
sh runAmase_WaterwaySearch.sh
python CheckFootprint.py

then press Play in AMASE, the Python script should output the coordinates
of the sensor footprint. You don't have to run UxAS for this example to
work.

**Comment by lhumphrey** [comment]
Rename the attached file as CheckFootprint.py and follow the previous instructions.
[CheckFootprint.txt](https://github.com/afrl-rq/OpenAMASE/files/2484761/CheckFootprint.txt)

**Comment by schoon1990** [comment]
> Rename the attached file as CheckFootprint.py and follow the previous instructions.
> [CheckFootprint.txt](https://github.com/afrl-rq/OpenAMASE/files/2484761/CheckFootprint.txt)

Perfect thank you! I'll check it out and see if it works for me. I will reply on this thread if it doesn't work.

**Comment by schoon1990** [comment]
Hello,

Thank you so much. Just a quick question, the set of lat/longs that is being generated in the terminal are the 4 corners of the polygon correct?
