### ISSUE TITLE
What am I doing wrong!

### ISSUE THREAD

**Issue by isonoe18** [afrl-rq/OpenAMASE#5]
Currently trying to get AMASE to work, I've followed the documentation the best I can but I am mildly confused on how to setup the application. I would like too, if possible, use this on macos would it be possible to just follow the linux instructions to achieve this or is it impossible. I also have a windows machine with a fresh install of both windows and java however i get this error whenever i run the openAMASE bat file.

Error: Could not find or load main class avtas.app.Application

any help would be greatly appreciated.
Also if i load an example file i get the splash screen appear but then the terminal closes instantly with no error that I can see.

**Comment by lhumphrey** [comment]
Hi there,

I can't help with Windows, but I run AMASE on Mac OS X. Which linux
instructions are you following?

I have cloned the OpenAMASE repository into ~/Documents/Git/OpenAMASE. On
my system, I can do the following in a terminal:
cd ~/Documents/Git/OpenAMASE/OpenAMASE/run/linux/Examples/
sh AutoZoneAvoidance.sh

This causes AMASE to start. From inside AMASE, I can select File > Open
Scenario. Then choose example scenarios > AutoZoneAvoidance.xml. This
should pull up a UAV and some no fly zones on the AMASE map. Then hit play
in AMASE to run a simulation.

If that does not work, you may not have built AMASE. Try the following
(adjusting paths to match your installation location):
cd ~/Documents/Git/OpenAMASE/OpenAMASE/
ant jar

You should see a bunch off build commands and flags ending in:
BUILD SUCCESSFUL
Total time: 0 second
